.circleci/config.yml
serverless.yml

These changes allow us to deploy to a staging and production environment with their own domain names, certificates, etc.
This app was forked from another HackIT app, the '[vulnerability checker](https://github.com/LBHackney-IT/housing-needs-vulnerabilities)'. These changes were necessary to distinguish it from that app.
These changes require new environment variables, which I have already added to the HackIT circleCI server.

Create new CI pipeline

---

serverless.yml

This PR changes the name of the Google groups (internal to Hackney) that are able to access this app.
(This previously being hard-coded to the 'wrong' value is the result of us forking an existing app.)

Change which groups can access the app

---

lib/dependencies.js
serverless.yml

Point these configuration values to keys that don't reflect the pre-fork version of this service. 
None of these keys existed in our AWS environment, so it was an opportunity to name them correctly!
At the time of writing, these SSM variables have been added in staging, but **not** in production.

Change Airtable configuration

---

.circleci/config.yml
next.config.js
pages/_document.js
pages/index.js

**What**  
Adds a Submit feedback btn to a google form and a HotJar tracking script
**Why**  
For user Testing

add hotjar and feeback google form btn

---

components/Layout/index.js
pages/index.js

This could be an environment variable, but given it was hard-coded in the repo we forked from, it might be it doesn't need to change often enough to justify it.
Given the other things we have to address, I'd rather change this to an env-var if it comes up again soon.

Change feedback form links

---

.circleci/config.yml
cypress/integration/features/editSnapshot.spec.js
cypress/integration/pages/snapshotSummary.spec.js
pages/snapshots/[id].test.js
setupTests.js

[These integration tests](https://github.com/LBHackney-IT/coronavirus-frontdoor-snapshot/blob/master/cypress/integration/pages/snapshotSummary.spec.js#L78)  currently rely on a `INH_URL` environment variable being a particular value. Since this variable is used to configure the real link that users see, I changed it to reflect our real environment - and the integration tests started failing.
This commit adds a hard-coded URL to the env vars passed to the integration tests, matching their expectations. I suspect there may be a better long-term way to do this.
(Unfortunately, the configuration in [setupTests.js](https://github.com/LBHackney-IT/coronavirus-frontdoor-snapshot/blob/master/setupTests.js) doesn't seem to affect the integration tests.)

Add static I-need-help URL for integration tests

---

.circleci/config.yml
components/Feature/TopicExplorer/index.js
components/Feature/TopicExplorer/index.test.js
cypress/integration/pages/home.spec.js
pages/index.js

This PR adds a section above the "resource finder", showing prompts based on a search.
____
Things we could do next:
- taking in markdown "additional information" underneath questions
- splitting this into multiple components
- more complicated search results than "a question"
- pulling results from airtable instead of a hardcoded hash
- fuzzy search
- more custom styling

Add basic version of conversational prompts

---

components/Feature/TopicExplorer/index.js
components/Feature/TopicExplorer/index.test.js
components/Feature/TopicExplorer/topics.js
package-lock.json
package.json
pages/index.js
yarn.lock

This version still pulls from hard-coded prompts rather than Airtable. 
I've tweaked the prompts so that this shows off the functionality a little better, and moved them to a flat file for easier future edits.
___
NEW:
OLD:

Add more information to conversational prompts w/Markdown

---

pages/stylesheets/all.scss

**What**  
The width of each resource should now stick to the 45% previously in place. Tags now wrap around on to another line if required.
The fix should look like the below:
**Why**  
So that the resources correctly display in 2 columns.
**Anything else?** 
N/A

Fix broken width caused by too many tags

---

components/Feature/TopicExplorer/index.js
cypress/integration/pages/home.spec.js

Since we're not connected to airtable prompts yet, the old terms didn't show any results. These new words have matches in the example prompts.
NEW:

Change placeholder search terms

---

components/Feature/TopicExplorer/topics.js

At the time of writing, we're working on making these accessible to everyone (by importing from Airtable).
In the meantime, it's a fairly quick job to make these more useful for research!

Add more 'testing' words to example prompt tags

---

components/Feature/TopicExplorer/index.js
cypress/integration/features/editSnapshot.spec.js
pages/index.js
pages/snapshots/[id].js

This PR adds the new conversational prompts to the 'edit snapshot' view, meaning that they'll be visible to people clicking through the 'I need help' service.
These being disparate views is likely to trip up other people in the future, but bringing those views together would take too much time right now, sadly.

Show prompts on call journey

---

components/Feature/TopicExplorer/index.js
components/Feature/TopicExplorer/index.test.js
cypress/integration/features/editSnapshot.spec.js
cypress/integration/pages/home.spec.js
pages/index.js
pages/stylesheets/all.scss

**What**  
This update reflects the findings in the research, with title updates, a title removed, and additional spacing added
**Why**  
To make the conversational prompt clearer for Agents to use
I also removed the horrible black outline that appeared when clicking on the 3 suggestions, plus attempted to update the cypress tests :-)

Update conversational prompt titles

---

pages/index.js
pages/stylesheets/all.scss

**What**  
The styling made the links look out of place. The styling has been updated to make them match the rest of the design.
Because the information is being pulled in from AirTable, I had to manipulate the styling on the classes/elements that were readily available, rather than create entirely new classes.
Old:
New:
**Why**  
To make the content match the rest of the design.

Update styling of listed links in conversational prompts

---

pages/stylesheets/all.scss

**What**  
This is a one-line css fix which prevents links in the expanded content from forcing wider widths.
Before:
After:
**Why**  
The current styling in place, allows long links to break the widths of the content areas.

Fix layout breaking for expanded content

---

pages/stylesheets/all.scss

**What**  
The conversational prompts icon is displaying locally but not in a staging environment. There is something to be understood around how static assets are compiled/served different locally compared to lambdas. As a quick fix, it is hoped that converting into base 64 encoded image will solve this issue.

Fix prompt icon in staging

---

components/Feature/VulnerabilitiesGrid/index.js
pages/stylesheets/all.scss

**What**  
Spacing between the resources and filters has been increased, padding to the right of the prompts has been added to reduce long line lengths
**Why**  
To improve legibility

add-padding-to-improve-spacing

---

pages/stylesheets/all.scss

**What**  
Some conversational prompts are displaying the wrong styling on links
**Why**  
For consistency

fix-incorrect-link-colours

---

components/Feature/TopicExplorer/index.js
cypress/integration/pages/home.spec.js

**What**  
The search was displaying the dropdown search options as soon as the user clicked on the search. This pr only displays search options when the user has typed something in the search box.
**Why**  
Allows users to use the search as it was intended and not as a dropdown.

Remove default dropdown from search

---

components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
pages/stylesheets/all.scss

**What**  
Some styling rules for cards were introduced, but they're targeted at classes that are the result of dynamic React rendering.
**Why**  
These'll be different for each card (and may not be deterministic), so not all cards will be correctly styled.

Remove dynamically rendered react classes from stylesheet

---

pages/loggedout/index.js

`NEXT_PUBLIC_URL` is returning undefined for a reason that's eluding me - I suspect it's that this env var isn't available client-side, but I haven't been able to resolve it in the time available.
This commit risks someone being directed to a live environment accidentally upon logging in, but I think it is worth the tradeoff for
users not getting stuck/confused after they login.
I also took the liberty of tweaking the language slightly - from talking about "logging in" to "signing in" instead.

Redirect to hard-coded path after signing in

---

components/CookieBanner/index.js
package.json
pages/_document.js
yarn.lock

Retrieved from the implementation at https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics.
This commit also removes the existing tag manager code, which wasn't working with Hackney's current GA setup.

Use _document tag for Google Analytics tracking code

---

.circleci/config.yml

**What**  
Set base url env var in circleCI
**Why**  
It's not currently being picked up because it needs to be set in the build stage

Set base url env var in circleCI

---

router/lambda.js

**What**  
Send back 403 for api paths instead of redirecting to /loggedout page
**Why**  
To api endpoints more consumable

Send back 403 for api paths instead of redirecting to /loggedout page

---

components/Feature/Services/index.js
cypress/integration/pages/home.spec.js

**What**  
Only display categories that have services associated with them:
Before:
After:
**Why**  
To remove irrelevant headings for empty categories

Filter accordion items to only display categories that contain services

---

.circleci/config.yml

**What**  
Set a different hotjar ID env var for production build
The script for hotjar already exists in `pages/_document.js`, this PR adds a separate hotjar ID for production
**Ticket**
https://trello.com/c/yuoJ5ur0

Set a different hotjar ID env var for production build

---

components/Feature/VulnerabilitiesGrid/ResourceCard/index.js

**What**  
Remove how to contact row from resource card as it would always default to 'self referral'
Remove opening times and current provision rows from resource card as we don't get that data from anywhere.
**Before:**
**After:**

Remove some unused fields from resource card

---

components/Feature/VulnerabilitiesGrid/ResourceCard/index.js

Co-authored-by: kosiakatrina <katrina@madetech.com>
**What**  
- add copy icon next to each service name
**Why**  
- to enable users to copy all service details to clipboard (see format below)
**Copy format**
```
Service Name: <>
Telephone: 88888888
Service Description: <general description>
Address: <address>
Description: <wider description>
Websites: <website>
Referral email: <email>
Referral website: <referral website>
```
**Link to ticket**
https://trello.com/c/JUef2YQv/122-as-a-hth-frontline-worker-i-need-to-send-residents-information-about-services-so-that-they-can-refer-themselves

Copy services to clipboard

---

lib/dependencies.js
lib/domain/referral.js
lib/gateways/models/createModelFromReferral.js
lib/gateways/referral-gateway.js
lib/gateways/referral-gateway.test.js
lib/infrastructure/logging/with-logging.js
lib/use-cases/create-referral.js
lib/use-cases/create-referral.test.js
pages/api/referrals/index.js
pages/api/referrals/index.test.js

**What**  
Make referral endpoint expect more params and save them and send an email
Now `POST` `http://localdev.hackney.gov.uk:3000/api/referrals` expects the following body
```json
{
"firstName": "Luna",
"lastName": "Kitty",
"phone": "57",
"email": "kegajaput@mailinator.net",
"address": "Camilla Wiggins",
"postcode": "Kato Contreras",
"referralReason": "Cum fugiat assumend",
"conversationNotes": "Expedita explicabo ",
"referrerName": "Solomon Payne",
"referrerEmail": "sihyvoriwa@mailinator.com",
"referrerOrganisation": "Bullock Malone Co",
"dateOfBirth": {
"year": "2015",
"month": "4",
"day": "28"
},
"serviceId": 123,
"serviceName": "Sun in my eyes",
"serviceContactEmail": "sun@eyes.com",
"serviceReferralEmail": "getsun@eyes.com"
}
```
**Why**  
so that we know what service residents …

Make a referral

---

pages/index.js

- Removed the 2nd feedback button (The massive green one at the bottom).
Before             |  After
:-------------------------:|:-------------------------:
- It was making the user journey more confusing by distracting from the support summary dropdown.
- Trello ticket number: [174](https://trello.com/c/NeryDgzl/174-remove-submit-feedback-button).
- No tests were associated with that button, hence only 1 file changed.

Removed a second (redundant) feedback button.

---

components/Layout/PhaseBanner/index.js
components/Layout/index.js

- Changed phase banner text from 'Alpha' to 'Beta'.
- Added disclaimer text to the banner saying that tool is a work in progress.
- It's been used (and hence tested) by users for some time now.
Before             |  After
:-------------------------:|:-------------------------:

Alpha to beta label and text

---

serverless.yml

**What**  
add metric filter to serverless yaml
**Why**  
To create a custom metric looking for errors in the CloudWatch log

add metric filter to serverless yaml

---

components/Feature/Services/index.js
components/Feature/SupportSummary/index.js
components/Feature/SupportSummary/index.module.scss
components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
components/Feature/VulnerabilitiesGrid/ResourceCard/index.module.scss
components/Feature/notification-messages.module.scss
cypress/integration/features/createSumarry.spec.js
cypress/integration/features/createSummary.spec.js
cypress/integration/pages/home.spec.js
lib/utils/analyticsConstants.js
lib/utils/getEmailBody.js
package.json
pages/index.js
yarn.lock

**What**  
Enable the removal of services added to the summary email:
Before:
After:
Add banner for when the service is checked:
Format the email:
Before:
After:
**Why**  
To make the summary emailing process easier and the page content more informative.

Summary email

---

components/Feature/ReferralForm/index.js
components/Feature/ResidentDetails/index.js
components/Feature/SupportSummary/index.js
cypress/integration/features/createReferral.spec.js

Make resident email non mandatory for referral forms and disable/uncheck sharing referral receipt with the resident when no email is entered

Make resident email non mandatory 

---

lib/utils/analyticsConstants.js
pages/_app.js
pages/index.js

**What**  
move onbeforeunload script  to the individual page instead of all of them
**Why**  
To avoid alert showing on privacy and logged out pages ([ticket](https://hackney.atlassian.net/jira/software/projects/HTHA/boards/57?selectedIssue=HTHA-119))

move onbeforeunload script 

---

components/Feature/ReferralForm/index.js
components/Feature/ResidentDetails/index.js
components/Feature/SupportSummary/index.js
cypress/support/commands.js

**What**  
Reduce accessibility violation threshold from 3 to 1, so that the automated tests fail if there's more than 1 accessibility violation.
The remaining violation that occurs is documented [here](https://dequeuniversity.com/rules/axe/4.1/region), and it is caused by SkipLink and PhaseBanner being outside of main or header content. It is a known issue with govuk frontend described [here](https://github.com/alphagov/govuk-frontend/issues/1604)
Update form labels.
**Why**  
To increase automated test coverage and confidence in application accessibility standards

Accessibility

---

lib/domain/referral.js
lib/gateways/referral-gateway.js
lib/gateways/referral-gateway.test.js
lib/utils/constants.js

**What**  
Added LinkId, ReferenceNumber, StatusHistory to referrals and generate initial values on create referral.
**Why**  
To allow us to send referral confirmation links to services so they can provide confirm/deny of a request.

Save link ids

---

lib/gateways/referral-gateway.js
lib/gateways/referral-gateway.test.js
lib/use-cases/update-referral.js
lib/use-cases/update-referral.test.js

**What**  
Change the existing update (formerly save) dynamodb gateway method to only update statusHistory.
**Why**  
Because this method is not currently being used and is no longer relevant - we only want to be able to update the statusHistory after the creation of the referral

Update status history

---

components/Feature/ReferralForm/index.js
pages/api/referrals/index.js

**What**  
Pass in the service description when creating a new referral
**Why**  
Resident email contained 'undefined' instead of service description, because of this bug

Pass serviceDescription to createReferral

---

config/tables/content/sent.json
cypress/integration/features/changeStatus.spec.js
lib/gateways/referral-gateway.js
lib/gateways/referral-gateway.test.js
lib/use-cases/create-referral.js
lib/use-cases/create-referral.test.js
lib/use-cases/send-referral-email.js
lib/use-cases/send-referral-receipt-email.js
lib/use-cases/send-referral-response-email.js
package.json
pages/referrals/status/[id].js

- Added Reference Number to Success confirmation message and Accepted/Rejected referral messages on Status Page.
- Added Reference Number parameter to "Referral" & "Referral Receipt" email templates.
- To share the common id between referrer & service.
- To have an identifier with which to chase up on at every stage of referral process.
- Moved out the generation of Reference Number from the 'referral-gateway' to the 'create-referral' use-case.
- Added a shorter command to start up the local "dynamodb" instance into node scripts.
- Added a <br/> newline because the automatic word wrapping was wrapping on the hyphens "-" within reference number.
- Added additional accessibility cypress checks within accept/reject referral tests for the way page is displayed after refresh. 
- Co-authored …

Add ref number to emails and receipts

---

package.json
pages/referrals/status/[id].js
yarn.lock

**What**  
html encode the comment using html-entities package before displaying on screen
Before:
After:
**Why**  
To reduce a possibility for XSS attacks
Add html-entities package
Removed license from package.json - we already specify it on line 4

html encode the comment using 

---

components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
components/Form/Details/index.js
components/Layout/Header/index.js
pages/_app.js
pages/index.js

**What**  
Remove accessibility issues discovered in accessibility assessment:
- Remove underline from non-link text
- Remove redundant link from hackney logo as there was also a link on `Support for Hackney residents` header
- Filter out empty error messages before displaying them as they were displaying as empty `span` elements and were being suggested as h1-h6 elements.
- Add fieldset to `share service with a resident` checkboxes
- Add external link icon
[BC2-62](https://hackney.atlassian.net/browse/BC2-62?atlOrigin=eyJpIjoiYjk5MGJkMDk3YTNiNGVhZmEzODI4ODM2OWVjNmIwNTciLCJwIjoiaiJ9)
**Why**  
To make the tool more accessible
Accessibility recommendations included removing noscript tag, but by doing that the UI tests get stuck when running on circle, so left the …

Accessibility fixes

---

lib/utils/search.js

**What**  
Check if synonyms env var is JSON before parsing it
Create synonyms parameter inside the getSearchResults method, because isJSON method is not available before init.
Pass synonyms into getWeight method
**Why**  
To avoid the page crashing if SYNONYMS isn't a JSON

Check if synonyms env var is JSON before parsing it

---

lib/utils/search.js

**What**  
Add synonym matching on full phrase
**Why**  
Previously if more than 1 word is entered in the search box it would try to find a synonym for each word only. Now it'll also try to find a synonym for a full phrase.

remove console logs and add synonym matching on full phrase

---

lib/utils/search.js
lib/utils/search.test.js
lib/utils/searchHelper.js

**What**  
- Now adds weight cumulatively rather than ordering by IsFullMatch, IsSingleWordMatch, IsSynonymMatch
- Weights Title matches higher than content.
- Weights results with a referral option higher than those without.
**Why**  
In order to provide more relevant results at the top we have improved ordering by relevance.

Improve search ordering

---

components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
components/Feature/VulnerabilitiesGrid/ResourceCard/index.module.scss
cypress/integration/pages/home.spec.js

- Removed the blue coloured tags from resource cards _(services from search results)_.
- Commented out green coloured council tags _(from the same place)_.
- The services listed within this application come from "Find Support Services" database. For some unclear reason when the data is being entered into FSS, it doesn't take advantage of one-to-many relationship between Organisation and Service tables.
As a result, every organisation within FSS has only 1 service, which is actually multiple services. This means that the description & **tags** of a single service we pull down actually contains information about multiple services that an organisation offers. It's a problem, because many organisations offer the same services, so when looking into search results, pretty much every service has …

Remove useless tags

---

styles/referralStatus.module.scss

- Changed "Accepted" My View page referral status tag to have green background colour.
- Aligned text to be centered within referral status tag.  
- I believe, this change was requested by user feedback. Or at least someone's feedback. Apart from that I don't believe there's anything extra in play apart from visual aesthetics.
Before            |  After
:-------------------------:|:-------------------------:
- Having green and red status bars was not considered an accessibility issue due to the text contained within status bar.
- Jira ticket: [106](https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=66&projectKey=BC2&modal=detail&selectedIssue=BC2-106).

Accept reject status bar styling

---

.circleci/config.yml
docs/development.md
package.json
seed-dynamo.sh
yarn.lock

- Created a bash script for automating the creation of local test DynamoDB tables & seeding data into them.
- Added the `yarn seed-dynamo` script.
- Added `yarn servers` script.
- Added `yarn cypress` script.
- Shortened CircleCI config.
- Updated `development.md` to reflect new yarn scripts available.
- Added script because the CCI config has become bulky & because I want to automate resetting test records' state after glitchy cypress test run.
- Added `seed-dynamo` so that it would be easy to use both from CircleCI config & from other yarn scripts.
- Added `servers` because I'm tired of having to open 3 terminal windows and run 3 yarn server scripts every day.
- Added `cypress` because I'm tired of wasting time trying to find out why the tests are failing only to find out it's because …

Automate db setup

---

pages/support-a-resident/index.js
public/js/beforeUnload.js

- Removed 'Leave site' warning that warns users about potentially losing data they have entered into the form.
- Remove function that enables this warning.
- Users have found this warning to be annoying. Presumably it has to do with the way they work: having a lot of application tabs open. When some get stale you just want to close them & not be bothered with a warning on every tab.
| Removed warning |
| -------- |
| ![image](https://user-images.githubusercontent.com/43747286/129713793-788aa42d-e36c-4c5e-b608-b5343c934379.png) |
- Jira ticket: [103](https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=66&projectKey=BC2&modal=detail&selectedIssue=BC2-103).

Removed 'Leave site' warning & function.

---

components/Feature/StatusForm/index.js
components/Feature/StatusForm/index.module.css
cypress/integration/features/changeStatus.spec.js
cypress/integration/pages/status.spec.js

- Made "reject reason" field mandatory upon selecting that referral was rejected _(Accept/Reject referral status page)_.
- Rejecting a referral without providing a reason does not give enough information of make informed decisions on whether to refer to organisation or how to refer to it in the future. For instance, if a company rejects a resident's referral, how should we know if that was because they: 
- don't have the capacity to book them over the coming week, or 
- need more information
- no longer provide the service that is being referred to?
| Reject reason field error upon clicking Submit without filling it in |
| --- |
| ![image](https://user-images.githubusercontent.com/43747286/129892049-47f86471-21da-4193-b05c-35aeebcd7d04.png) |
Jira ticket: …

Make reject referral required and styled

---

components/Feature/ResourceCard/index.js
components/Feature/Services/Categories/index.js
components/Feature/Services/index.js
lib/utils/search.js
lib/utils/search.test.js
lib/utils/searchHelper.js

**What**  
Highlight categories within service description if no search term is entered.
Weight the resources with categories within the descriptions higher.
**Why**  
To make the category search more valuable and accurate and increase user confidence in the results.
Add to the current weight when calling `weightByCategories` instead of resetting the weight
Get the average of the weights when flattening the resources instead of getting the first one
Log selectedCategories as names instead of IDs to enable searching by categories

Highlight categories

---

components/Feature/Services/index.js
components/Feature/Services/index.module.scss

**What**  
Added a grey background to the personalisation panel.
**Why**  
The search and search results weren't visually separate and made it difficult to separate functionality for users.

Added grey background to personalise panel
