LBHackney-IT/coronavirus-frontdoor-snapshot

- pages/index.js
**What**  
{summarise your PR and what it is for, add a screenshot for UI changes}
**Why**  
{why are we making this change?}
> open link in new tab

- components/Form/CheckboxList/index.js
- pages/stylesheets/all.scss
> Remove custom colour from checkboxes

- README.md
- cypress/integration/features/editSnapshot.spec.js
- cypress/integration/pages/snapshotSummary.spec.js
- lib/use-cases/find-snapshots.js
- next.config.js
- pages/snapshots/[id].js
- serverless.yml
**What**  
Adds a continue to INH button
**Why**  
Part of the bigger picture of delivering the End to end user journey
https://trello.com/c/RDdaOxJG/77-the-ability-to-proceed-to-snapshot-from-inh-linking-residents-data
> 77 the ability to proceed to snapshot from inh

- components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
- components/Feature/VulnerabilitiesGrid/index.js
- pages/stylesheets/all.scss
**What**  
Remove some additional margin from heading where it was not needed.
**Why**  
Improve the design
> Remove unnecessary margin

- components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
- components/Feature/VulnerabilitiesGrid/index.js
**What**  
Adds bottom margin for resources which contain a summary bellow the heading. This was removed by the previous pr as summary information outside the food resources were not accounted for. 
**Why**  
For consistency and to improve readability and user experience.
> Improve header layout

- components/Feature/TopicExplorer/index.js
- components/Feature/TopicExplorer/index.test.js
- pages/index.js
- pages/snapshots/[id].js
This is a rebased version of #34. I worked in the same area and caused some merge conflicts. Oops.
More prompts! Great big lists of prompts!
(now from Airtable, so they can be updated without coding needed! :tada:)
_____
> Hook up topic explorer to airtable (w/conflicts fixed)

- components/Feature/TopicExplorer/index.js
**What**  
This adds "coronavirus" as an option above the search tool
**Why**  
Because it's a hot topic!
> add-new-search-option

- components/Feature/TopicExplorer/index.js
- components/Feature/TopicExplorer/index.test.js
**What**  
This pr introduces a dropdown in the search which dynamically updates with the search. It pulls all the search terms from air-table
**Why**  
This will allow users to anticipate the search terms
> Add autocomplete dropdown and improved search

- pages/loggedout/index.js
This PR tries to make the next steps more obvious for someone who arrives at the snapshot but isn't logged in.
> Better "You can't access the service" page

- cypress/integration/pages/home.spec.js
- serverless.yml
**What**  
Extract allowed groups into an ssm variable
**Why**  
So that different groups could be easily set for different stages
> Extract allowed groups into a variable

- lib/gateways/airtable-gateway.js
- lib/gateways/airtable-gateway.test.js
- lib/gateways/fss-resources-gateway.js
- pages/index.js
- pages/snapshots/[id].js
**What**  
Add basic try catch blocks to the gateways and make them return empty arrays on failure 
Only concatenate the resources if they exist
**Why**  
To prevent the whole application from crashing if just one source errors out.
> Add error handling

- README.md
- lib/dependencies.js
**What**  
- Pass logger into the create Referral use case - otherwise it throws "Cannot read property 'info' of undefined" error when trying to save new record to the db
- Update readme with the new table name vulnerabilities.json => referrals.json
> Fix logger error

- .circleci/config.yml
- components/Feature/ResidentDetailsForm/index.js
- components/Feature/Services/index.js
- components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
- components/Feature/VulnerabilitiesGrid/ResourceCard/index.module.scss
- components/Feature/VulnerabilitiesGrid/index.js
- lib/api/utils/useReferral.js
- pages/index.js
**What**  
Return result from createReferral (currently returns an object with id if record in the database was created)
If ID exists set success message for the referral
> Successful referral message

- .circleci/config.yml
- components/Feature/ResidentDetailsForm/index.js
- components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
- components/Feature/VulnerabilitiesGrid/ResourceCard/index.module.scss
- cypress/integration/features/createReferral.spec.js
- lib/dependencies.js
- lib/domain/referral.js
- lib/gateways/notify-gateway.js
- lib/gateways/referral-gateway.js
- lib/use-cases/create-referral.js
- lib/use-cases/create-referral.test.js
- lib/use-cases/send-referral-receipt-email.js
- lib/use-cases/send-referral-receipt-email.test.js
- mock-server/stubs/__files/service_directory.json
- pages/api/referrals/index.js
- pages/index.js
**What**  
**Why**  
show red error message if an error occur, show green message if success. 
send email receipt to user after sending referral email
> Make a referral send

- router/lambda.js
- serverless.yml
**What**  
typo(?) fix
Add referrals route to basic permissions
> Change env var name

- .circleci/config.yml
- components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
- lib/use-cases/create-referral.js
- next.config.js
- pages/index.js
**What**  
removed referral feature flag
**Why**  
we're ready to prod 🎉 🚀 
> remove feature flag

- components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
- cypress/integration/pages/home.spec.js
- lib/domain/resource.js
- lib/gateways/fss-resources-gateway.js
- lib/gateways/models/createResourceFromModel.js
- lib/gateways/models/createResourceFromModel.test.js
- mock-server/stubs/__files/fss_services.json
- mock-server/stubs/__files/service_directory.json
**What**  
Rename and add missing relevant fields to the resource card
Before:
After:
**Ticket**
https://trello.com/c/nQEl9Zgz
> Rename and add missing fields to the resource card

- .circleci/config.yml
- components/Feature/ResidentDetailsForm/index.js
- components/Feature/Services/index.js
- components/Feature/SupportSummary/index.js
- components/Feature/TopicExplorer/index.js
- components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
- components/Feature/VulnerabilitiesGrid/ResourceCard/index.module.scss
- components/Feature/notification-messages.module.scss
- components/Form/Details/index.js
- components/Form/TextArea/index.js
- components/Form/TextInput/index.js
- components/Heading/index.js
- cypress/integration/pages/home.spec.js
- lib/api/index.js
- lib/api/utils/useConversation.js
- lib/utils/getEmailBody.js
- pages/index.js
**What**  
Add basic step by step navigation
Add summary form for sending summaries to the residents
**Ticket**
https://trello.com/c/tKu83YmA
> Summary form

- docs/Architecture.md
- docs/Data-Flow.iuml
**What**  
{summarise your PR and what it is for, add a screenshot for UI changes}
Add a diagram to show the architecture for the Better Conversations application
**Why**  
{why are we making this change?}
To build up better documentation
**Anything else?**
> Add Architecture Diagram

- components/Feature/ResidentDetailsForm/index.js
- components/Feature/SupportSummary/index.js
**What**  
Move the screen view to resident form when sumbit is clicked and residentInfo is empty
Check all of the residentInfo fields before displaying the summary form
> Move up to resident form

- components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
- components/Feature/VulnerabilitiesGrid/index.test.js
- cypress/integration/pages/home.spec.js
- lib/domain/resource.js
- lib/gateways/airtable-gateway.js
- lib/gateways/models/createResourceFromModel.js
- mock-server/stubs/__files/service_directory.json
**What**  
Display different tags from secret services instead of labelling them all as 'Council' services
https://trello.com/c/XOJDIqgC
> Council tags

- components/Layout/Footer/index.js
- cypress/integration/features/createReferral.spec.js
- pages/privacy/index.js
- router/lambda.js
**What**  
Add a privacy statement page and link out to it from the footer. Should be accessible to the users that are not logged in as well
https://trello.com/c/yGkKmbGE
> Privacy page

- .circleci/config.yml
- components/Feature/SupportSummary/index.js
- components/Form/Details/index.js
- cypress/integration/features/createSumarry.spec.js
- pages/index.js
**What**  
testing and releasing summary emails 
**Why**  
{why are we making this change?}
> Release summary

- cypress/integration/pages/home.spec.js
- lib/utils/search.js
- lib/utils/search.test.js
- lib/utils/synonyms.json
- mock-server/stubs/__files/fss_services.json
**What**  
add synonym search using words in synonym.json file (currently only containing a test term and depression => mental health mappings)
**Why**  
To enable more thorough search
> Add synonym search for individual words

- cypress/integration/features/createSumarry.spec.js
- lib/use-cases/create-referral.js
- lib/use-cases/create-referral.test.js
- lib/use-cases/send-referral-resident-email.js
- lib/utils/getEmailBody.js
**What**  
Update resident emails to include response email disclaimer
**Why**  
To prevent the residents from replying to the generic sender email
> Update resident emails to include response email disclaimer

- components/Feature/Services/Categories/CategoryCard/index.js
- components/Feature/Services/Categories/CategoryCard/index.module.scss
- components/Feature/Services/Categories/index.js
- components/Feature/Services/index.js
Highlight the selected category and make category card corners round
> Highlight the selected category and make category card corners round

- components/Feature/ReferralForm/index.js
- components/Feature/Services/Categories/CategoryCard/index.js
- components/Feature/Services/index.js
- components/Feature/SupportSummary/index.js
- cypress/integration/features/createReferral.spec.js
- cypress/integration/features/createSummary.spec.js
- cypress/integration/pages/home.spec.js
- cypress/support/commands.js
**What**  
Add automated accessibility tests to cypress
Currently the violation threshold is set to 3, but should be set to reduce in the future
**Why**  
To prevent future accessibility violations more easily
> Automated accessibility tests

- components/Feature/VulnerabilitiesGrid/grid.json
- cypress/plugins/index.js
- package.json
Add and run a formatter command
> Add and run a formatter command

- lib/gateways/referral-gateway.js
- lib/gateways/referral-gateway.test.js
- lib/use-cases/create-referral.js
- lib/use-cases/create-referral.test.js
- lib/use-cases/send-referral-email.js
**What**  
Extract linkId from referrals gateway to the create referral use case
Pass status link to the referral email as govnotify personalisation
**Why**  
To enable the services to locate the status page for the referral
> Send status link

- serverless.yml
**What**  
Allow patching status without auth
**Why**  
The path is currently behind authoriser
> Allow patching status without auth

- components/Feature/Services/index.js
- components/Feature/VulnerabilitiesGrid/ResourceCard/index.js
- cypress/integration/pages/home.spec.js
- lib/utils/search.js
- lib/utils/search.test.js
**What**  
Highlight search terms in the results. Highlight:
- full search term (lowercase, uppercase, capitalised)
- individual words (excluding short words) (lowercase, uppercase, capitalised)
- synonyms (lowercase, uppercase, capitalised)
**Why**  
To interpret the result easier
> Search result highlighting

- components/Layout/PhaseBanner/index.js
- components/Layout/index.js
**What**  
Add feedback link into the phase banner
**Why**  
To allow users/services to log their feedback
> Add feedback banner

- cypress/integration/features/createReferral.spec.js
- cypress/integration/pages/home.spec.js
**What**  
Reduce the time it takes for the UI tests to run:
Locally:
createReferral ~105s -> ~27s
home ~46s -> ~10s
On circleCI (UI tests only):
~200s -> ~122s
**Why**  
To speed up the deployment pipeline
> Faster tests
